<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PMK | Application Form</title>
    <!-- Linked favicon  -->
    <link rel="shortcut icon" href="../assets/logo/main-logo.png" type="image/x-icon">
    <!-- linked custom css  -->
    <link rel="stylesheet" href="../styles/index.css">
    <link rel="stylesheet" href="../styles/apply.css">
</head>

<body>
    <main>
        <section id="job-application">
            <div class="application-header">
                <figure class="org-logo">
                    <img src="../assets/logo/main-logo.png" alt="pmk-log">
                </figure>

                <hgroup class="apply-header-content">
                    <h3 class="apply-header-title">Complete Your Job Application</h3>
                    <p class="apply-header-description">Complete your profile accurately to submit your job application successfully at PMK following all provided instructions carefully.</p>
                </hgroup>
            </div>

            <form action="" method="" id="application-form">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil totam nostrum tenetur laborum dicta consectetur distinctio numquam aut repudiandae laboriosam dignissimos dolore ullam alias, quia aliquam obcaecati, itaque quis? Similique beatae praesentium aliquid sit. Quaerat quibusdam amet reiciendis id fugiat, eos necessitatibus ducimus ex eum commodi corrupti laborum? Totam, fuga.</p>
            </form>
        </section>
    </main>
</body>

</html>